// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XXb2Q7gMQH2zaSjRm4ajvJrwTprElrI',
    appId: '1:414714682289:web:87a8465cbb6ee076effb90',
    messagingSenderId: '414714682289',
    projectId: 'chat-1cb46',
    authDomain: 'chat-1cb46.firebaseapp.com',
    storageBucket: 'chat-1cb46.appspot.com',
    measurementId: 'G-NDNP9W2YS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9rdaTVKeefLFl7osFguaa5lDLi4F9DA',
    appId: '1:414714682289:android:260fa09a4ad683e6effb90',
    messagingSenderId: '414714682289',
    projectId: 'chat-1cb46',
    storageBucket: 'chat-1cb46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSIlQ5oc965YJeHjQbm6IPW5BEQS0fX18',
    appId: '1:414714682289:ios:6a9e3647a423fd68effb90',
    messagingSenderId: '414714682289',
    projectId: 'chat-1cb46',
    storageBucket: 'chat-1cb46.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSIlQ5oc965YJeHjQbm6IPW5BEQS0fX18',
    appId: '1:414714682289:ios:6a9e3647a423fd68effb90',
    messagingSenderId: '414714682289',
    projectId: 'chat-1cb46',
    storageBucket: 'chat-1cb46.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8XXb2Q7gMQH2zaSjRm4ajvJrwTprElrI',
    appId: '1:414714682289:web:0a4402dd4627ee31effb90',
    messagingSenderId: '414714682289',
    projectId: 'chat-1cb46',
    authDomain: 'chat-1cb46.firebaseapp.com',
    storageBucket: 'chat-1cb46.appspot.com',
    measurementId: 'G-R417VENDFT',
  );

}